### ISSUE TITLE
error script workflow.py: index out of range

### ISSUE THREAD

**Issue by Otavio20** [Finn-Lab/EukCC#11]
Dear all,

I'm facing issues with the script workflow.py as pointed bellow: 
![error](https://user-images.githubusercontent.com/46409628/95665850-75557980-0b2a-11eb-987a-078b0df33369.png)

It is occurring even when the GeneMark-ES predict proteins.
Thanks in advance.

**Comment by openpaul** [comment]
Thanks for reporting this. Seeing all the warnings about 'taxid not found' I would suggest you should update the ete3 NCBI taxonomy database. 

http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html#upgrading-the-local-database

This should fix the issue, but I also am working on a fix for this but will first need to run some tests before creating a new version (see commit: 425f3cb1ff184364cc3f19e7208bd8ba31a5cf2d).  If you are familiar with python feel free to compile the package from the dev branch and test it.

The error occurs because ete3 cant compute lineages for any node, leaving EukCC without any information to infer the LCA for your MAG.

**Comment by Otavio20** [comment]
It worked!

Thank you very much!
