### ISSUE TITLE
Further guidance on GeneMark-ES installation

### ISSUE THREAD

**Issue by mw55309** [Finn-Lab/EukCC#21]
Hey

Great tool!

It would be great if the documentation around installation of GeneMark-ES could be expanded.

For example, "apt" is not installed on our Linux cluster ;-)

Given the conda install, it would be good if some kind of recipe for using conda or pip could be implemented, including the ability to install non-system libraries (i.e. install perl libs into home directories)

Cheers
Mick

**Comment by openpaul** [comment]
Hello, apt is the package manager of Debian and Ubuntu. This will only be possible if you have root access to your server. All the documentation tells you to do, is to install perl correctly in order to run GeneMark-ES.

If you need help installing GeneMark-ES, you will need to look for help on their end (we do not provide GeneMark-ES, thats unrelated software).

Have a look around here:
http://exon.gatech.edu/GeneMark

Sadly I could not make perl work only using conda on my end, thats why I suggest installation of cpanminus via apt. If you succeed, feel free to share and I will try to validate your approach.

**Comment by mw55309** [comment]
My very quick test shows this works to get GeneMark-ES running:

```sh
conda install perl-app-cpanminus

env PERL5LIB="" PERL_LOCAL_LIB_ROOT="" PERL_MM_OPT="" PERL_MB_OPT="" $CONDA_PREFIX/bin/cpanm inc::Module::Install::DSL Hash::Merge MCE::Mutex FindBin Test::Pod Logger::Simple  Parallel::ForkManager.pm YAML Math::Utils
```

Note1 you could add perl-app-cpanminus to the eukcc conda recipe

Note2 you're missing Math::Utils from your list of required Perl libs

**Comment by openpaul** [comment]
Thanks a lot. `Math::Utils` must have slipped through the cracks. Thank you for finding this.

I am currently building a container trying to verify that this works.
